separator = "~fides_delim~"
field = [1]
normalize = true
extension = "weights"
distance.default = 7

[rule]
mode = "E"
text = "aliexpress.com"
weight = 1000

[suffix.pack]
weight = 1
distance.default = 5

[suffix.enegizer]
weight = 2
distance.left = 3


[suffix.aliexpress]
weight = 10
distance.right = 6
