separator = "¬~"
field = [2]
normalize = true
extension = "weights"
distance.default = 10

[rule]
mode = "E"
text = "hotel"
weight = 20

[suffix.instagram]
weight = 10
distance.default = 10

[suffix.tanzania]
weight = 5
distance.default = 10
